### PR TITLE
Update linter.rb add eyaml extension

### PR DESCRIPTION
**Pull request by rhyspowell**
We add the extension eyaml to our encrypted yaml files. This allows them to be tested

### CODE REVIEW

**Comment by shortdudey123** [comment]
Not sure we should allow custom extensions to be hard coded in.  Your custom extension might be someone else's typo.

That being said, I think custom extensions should be allowed.  3 thoughts for you:
- Allow disabling of extension checks
- Add CLI flag and rake option to allow adding of allowed extensions
- Add CLI flag and rake option to allow for the eyaml extension (i see several projects use it including https://github.com/TomPoulton/hiera-eyaml)

Thoughts? Any or all work for me :)

**Comment by ingydotnet** [comment]
I mentioned to @shortdudey123 on irc (#yaml freenode) that the extension `.yaml.crypt` (or similar) might be more appropriate. This has prior art as in `.tar.gz` for when you are stacking formats. It implies the after decryption you get `.yaml`.

**Comment by shortdudey123** [comment]
Added an option to disable the extension check in https://github.com/shortdudey123/yamllint/pull/5

**Comment by shortdudey123** [comment]
Added an option for custom extensions in https://github.com/shortdudey123/yamllint/pull/6

**Comment by shortdudey123** [comment]
closing since this 2 alternative options have been added

**Comment by shortdudey123** [comment]
above 2 alternative are published in v0.0.4

**Pull request closed without merging**
